# Generated by Django 5.1.7 on 2025-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
